apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication
  labels:
    app: user-authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-authentication
  template:
    metadata:
      labels:
        app: user-authentication
    spec:
      containers:
      - name: user-authentication
        image: gcr.io/carbon-zone-377308/users_authentication:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.1"
            memory: "64Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: gcr-secret
