apiVersion: v1
kind: Service
metadata:
  name: user-authentication
  labels:
    app: user-authentication
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: user-authentication
