apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-management
  labels:
    app: hotel-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-management
  template:
    metadata:
      labels:
        app: hotel-management
    spec:
      containers:
      - name: hotel-management
        image: gcr.io/carbon-zone-377308/hotel_manage:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.05"
            memory: "32Mi"
          limits:
            cpu: "0.2"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: gcr-secret
