apiVersion: v1
kind: Service
metadata:
  name: hotel-reservations
  labels:
    app: hotel-reservations
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: hotel-reservations
