apiVersion: v1
kind: Service
metadata:
  name: hotel-authentication
  labels:
    app: hotel-authentication
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: hotel-authentication
