image:
  repository: gcr.io/carbon-zone-377308/hotel_manage:latest
  tag: latest
service:
  name: hotel-management
  port: 5000
  type: ClusterIP
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
