image:
  repository: gcr.io/carbon-zone-377308/users_authentication
  tag: latest
service:
  name: user-authentication
  port: 5000
  type: ClusterIP
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
