apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-users
  namespace: 	hotelusers
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: api-users.birdbook.live
    http:
      paths:
      - pathType: Prefix
        path: "/users"
        backend:
          service:
            name: user-authentication
            port:
              number: 80
      - pathType: Prefix
        path: "/search/hotels"
        backend:
          service:
            name: user-search
            port:
              number: 80
      - pathType: Prefix
        path: "/reserve"
        backend:
          service:
            name: user-reserve
            port:
              number: 80    
      - pathType: Prefix
        path: "/reservations"
        backend:
          service:
            name: user-reserve
            port:
              number: 80   