apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-authentication
  labels:
    app: hotel-authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-authentication
  template:
    metadata:
      labels:
        app: hotel-authentication
    spec:
      containers:
      - name: hotel-authentication
        image: gcr.io/carbon-zone-377308/hotel_authenticate
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: gcr-secret