apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-search
  labels:
    app: user-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-search
  template:
    metadata:
      labels:
        app: user-search
    spec:
      containers:
      - name: user-search
        image: gcr.io/carbon-zone-377308/users_search:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.05"
            memory: "32Mi"
          limits:
            cpu: "0.2"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: gcr-secret
