name: Build and Deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: 	carbon-zone-377308
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with gcloud
      run: |
        gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
        gcloud auth configure-docker
  
    - name: Configure kubectl
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials gke-hmc --region europe-west8 --project carbon-zone-377308

    - name: Build and push Docker authentication image
      run: |
        gcloud builds submit --config ./K8sYaml/cloudbuild.yaml --project carbon-zone-377308

    - name: Set build status
      id: build_status
      run: echo "::set-output name=build_succeeded::true"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
          gcloud auth configure-docker
    
      - name: Configure kubectl
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials gke-hmc --region europe-west8 --project carbon-zone-377308

      - name: Deploy to GKE - Hotel Managers Namespace
        run: |
          helm upgrade authentication-chart ./Helm_Chart/authentication-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
          helm upgrade manage-chart ./Helm_Chart/manage-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
          helm upgrade occupancy-chart ./Helm_Chart/occupancy-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
          helm upgrade reservation-chart ./Helm_Chart/reservation-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
      - name: Deploy to GKE - Hotel Users Namespace
        run: |          
          helm upgrade uauth-chart ./Helm_Chart/uauth-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelusers          
          helm upgrade usersearch-chart ./Helm_Chart/usersearch-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelusers
          helm upgrade userreserve-chart ./Helm_Chart/userreserve-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelusers          
      - name: Deploy to GKE - Ingress Resource
        run: |          
          kubectl apply -f ./K8sYaml/ingress-resource-users.yaml --namespace hotelusers
          kubectl apply -f ./K8sYaml/ingress-resource-managers.yaml --namespace hotelmanagers
