name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with gcloud
      run: |
        gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
        gcloud auth configure-docker
  
    - name: Configure kubectl
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials gke-hmc --region europe-west8 --project carbon-zone-377308

    - name: Build and push Docker authentication image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest ./authentication
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest
    - name: Build and push Docker managers image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest ./manage
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest
    - name: Build and push Docker occupancy image
      run: |        
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_occupancy:latest ./occupancy
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_occupancy:latest
    - name: Build and push Docker users_auth image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/users_authentication:latest ./Uauthentication
        docker push gcr.io/${{ env.PROJECT_ID }}/users_authentication:latest

    - name: Set build status
      id: build_status
      run: echo "::set-output name=build_succeeded::true"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
          gcloud auth configure-docker
    
      - name: Configure kubectl
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials gke-hmc --region europe-west8 --project carbon-zone-377308

      - name: Deploy to GKE
        run: |
          helm upgrade authentication-chart ./Helm_Chart/authentication-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
          helm upgrade manage-chart ./Helm_Chart/manage-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
          helm upgrade occupancy-chart ./Helm_Chart/occupancy-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers
          helm upgrade uauth-chart ./Helm_Chart/uauth-chart --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers


