name: Build and push Docker image

on:
  push:
    branches: [main]

env:
  PROJECT_ID: your-project-id

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with gcloud
      run: |
        gcloud auth activate-service-account --key-file=.github\workflows\carbon-zone-377308-11e3fe73075a.json
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest ./authenticate
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest

        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest ./manage
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest
