name: Build and push Docker image

on:
  push:
    branches: [main]

env:
  PROJECT_ID: 	carbon-zone-377308

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with gcloud
      run: |
        gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
        gcloud auth configure-docker
  
    - name: Configure kubectl
      run: |
        sudo apt-get update && sudo apt-get --only-upgrade install google-cloud-sdk-package-go-module google-cloud-sdk-config-connector google-cloud-sdk-terraform-tools google-cloud-sdk-minikube google-cloud-sdk-app-engine-python-extras google-cloud-sdk-log-streaming google-cloud-sdk-local-extract google-cloud-sdk-kubectl-oidc google-cloud-sdk-datastore-emulator google-cloud-sdk-gke-gcloud-auth-plugin google-cloud-sdk-app-engine-go google-cloud-sdk-harbourbridge google-cloud-sdk-cbt google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-grpc google-cloud-sdk-kpt google-cloud-sdk-cloud-build-local kubectl google-cloud-sdk-anthos-auth google-cloud-sdk google-cloud-sdk-spanner-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-app-engine-java google-cloud-sdk-cloud-run-proxy google-cloud-sdk-enterprise-certificate-proxy google-cloud-sdk-nomos google-cloud-sdk-firestore-emulator google-cloud-sdk-bigtable-emulator google-cloud-sdk-skaffold



    - name: Build and push Docker authentication image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest ./authentication
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest
    - name: Build and push Docker managers image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest ./manage
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest
    - name: Build and push Docker occupancy image
      run: |        
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_occupancy:latest ./occupancy
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_occupancy:latest
    - name: Build and push Docker users_auth image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/users_authentication:latest ./Uauthentication
        docker push gcr.io/${{ env.PROJECT_ID }}/users_authentication:latest

    - name: Build and push Docker users_auth image
      run: |
         helm upgrade authentication-chart ./authentication/authentication-chart-0.1.0.tgz --set imagePullSecrets[0].name=gcr-secret --namespace hotelmanagers

