name: Build and push Docker image

on:
  push:
    branches: [main]

env:
  PROJECT_ID: 	carbon-zone-377308

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with gcloud
      run: |
        gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest ./authentication
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_authenticate:latest

        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest ./manage
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_manage:latest
        
        docker build -t gcr.io/${{ env.PROJECT_ID }}/hotel_occupancy:latest ./occupancy
        docker push gcr.io/${{ env.PROJECT_ID }}/hotel_occupancy:latest

        docker build -t gcr.io/${{ env.PROJECT_ID }}/users_authentication:latest ./Uauthentication
        docker push gcr.io/${{ env.PROJECT_ID }}/users_authentication:latest
