name: Build, Push to GCR and Deploy to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: carbon-zone-377308

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push to GCR
        uses: actions/github-script@v4
        with:
          script: |
            const { spawnSync } = require('child_process');
            const buildProcess = spawnSync('yarn', ['run', 'build'], { stdio: 'inherit' });
            const deployProcess = spawnSync('yarn', ['run', 'deploy'], { stdio: 'inherit' });
            if (buildProcess.status !== 0) process.exit(buildProcess.status);
            if (deployProcess.status !== 0) process.exit(deployProcess.status);

      - name: Include build.yaml
        uses: actions/github-script@v4
        with:
          script: |
            const { readFileSync } = require('fs');
            const buildYaml = readFileSync('build.yaml', 'utf8');
            return {
              buildYaml,
            };

      - name: Build and Push to GCR
        run: |
          echo "$buildYaml" > build.yaml
          envsubst < build.yaml > build.yaml.tmp && mv build.yaml.tmp build.yaml
          docker login -u _json_key -p "$(cat carbon-zone-377308-5fd1eaf197a3.json)" https://gcr.io
          cat build.yaml
          docker-compose -f build.yaml up --exit-code-from build

      - name: Include deploy.yaml
        uses: actions/github-script@v4
        with:
          script: |
            const { readFileSync } = require('fs');
            const deployYaml = readFileSync('deploy.yaml', 'utf8');
            return {
              deployYaml,
            };

      - name: Deploy to GKE
        run: |
          echo "$deployYaml" > deploy.yaml
          envsubst < deploy.yaml > deploy.yaml.tmp && mv deploy.yaml.tmp deploy.yaml
          gcloud auth activate-service-account --key-file=carbon-zone-377308-5fd1eaf197a3.json
          gcloud auth configure-docker
          kubectl apply -f deploy.yaml
